[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  
[[redirects]]
  from = "/assets/*"
  to = "https://devpredeploymentfixes-locator-booker-co-uk-pagescdn-com.preview.pagescdn.com/assets/:splat"
  status = 200
  force = true
  headers = {}
  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://devpredeploymentfixes-locator-booker-co-uk-pagescdn-com.preview.pagescdn.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://devpredeploymentfixes-locator-booker-co-uk-pagescdn-com.preview.pagescdn.com/"}
  
[[redirects]]
  from = "/subdirectory"
  to = "https://devpredeploymentfixes-locator-booker-co-uk-pagescdn-com.preview.pagescdn.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://devpredeploymentfixes-locator-booker-co-uk-pagescdn-com.preview.pagescdn.com/"}
